### PR TITLE
NNVP-120 Bisnode API

### PR DESCRIPTION
**Pull request by jnsvd**

### CODE REVIEW

**Comment by jnsvd** [comment]
:star: PR built and available in a preview environment **the-glue-nnvp-backend-pr-62** [here](http://nnvp-backend.jx-the-glue-nnvp-backend-pr-62.cluster.development.nnvp.thegluesandbox.com)

**Comment by jnsvd** [comment]
:star: PR built and available in a preview environment **the-glue-nnvp-backend-pr-62** [here](http://nnvp-backend.jx-the-glue-nnvp-backend-pr-62.cluster.development.nnvp.thegluesandbox.com)

**Comment by jnsvd** [comment]
:star: PR built and available in a preview environment **the-glue-nnvp-backend-pr-62** [here](http://nnvp-backend.jx-the-glue-nnvp-backend-pr-62.cluster.development.nnvp.thegluesandbox.com)

**Comment by piotr-milanski** [comment]
Another correct PR was created.

**Pull request closed without merging**
